package com.sentori

import java.io.File
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

/**
 * The Kotlin hash must equal the TypeScript one for every input, or a
 * device stops matching the events from the same person and the push
 * meant for them reaches nobody — silently, on the one path where
 * nobody is watching.
 *
 * The vectors are generated by `sdk/core/src/identity.ts` itself
 * (`scripts/gen-identity-vectors.mjs`), so this asserts against what
 * the other implementations actually do rather than against what this
 * file's author believed they do. It has already earned its keep:
 * Kotlin's default `trim()` leaves U+00A0 and U+FEFF in place where
 * JavaScript and Swift strip them, and the vector caught it before it
 * shipped.
 */
@RunWith(RobolectricTestRunner::class)
class SentoriIdentityTest {

    private fun vectors(): List<Triple<String, String, String>> {
        // Walk up out of the module to the fixtures shared with iOS.
        // Robolectric runs with the module directory as CWD; both the
        // native module and the React Native mirror of it sit three
        // levels below `sdk`.
        var dir = File(System.getProperty("user.dir") ?: ".").absoluteFile
        var fixture: File? = null
        repeat(8) {
            val candidate = File(dir, "sdk/native/fixtures/identity-vectors.json")
            if (candidate.exists()) {
                fixture = candidate
                return@repeat
            }
            dir = dir.parentFile ?: dir
        }
        val f = requireNotNull(fixture) {
            "identity-vectors.json not found above ${System.getProperty("user.dir")}"
        }
        val root = JSONObject(f.readText()).getJSONArray("vectors")
        return (0 until root.length()).map { i ->
            val v = root.getJSONObject(i)
            Triple(v.getString("keyType"), v.getString("raw"), v.getString("sha256Hex"))
        }
    }

    @Test
    fun matchesTheTypeScriptImplementation() {
        val vectors = vectors()
        // A fixture that read as empty would pass every assertion
        // below without running one.
        assertTrue("fixture looks truncated: ${vectors.size}", vectors.size >= 12)
        for ((keyType, raw, expected) in vectors) {
            assertEquals(
                "$keyType / ${raw.take(40)}",
                expected,
                SentoriIdentity.hash(keyType, raw),
            )
        }
    }

    @Test
    fun emptyAndBlankProduceNoKey() {
        assertNull(SentoriIdentity.hash("id", ""))
        assertNull(SentoriIdentity.hash("id", "   "))
        assertNull(SentoriIdentity.hash("id", null))
        assertNull(SentoriIdentity.hash("email", " \n "))
        // A phone with no digits normalises away entirely.
        assertNull(SentoriIdentity.hash("phone", "(--) --"))
    }

    @Test
    fun userKeyPrefersIdAndFallsBackToEmail() {
        assertEquals(
            SentoriIdentity.hash("id", "usr_123"),
            SentoriIdentity.userKey("usr_123", "a@b.com"),
        )
        assertEquals(
            SentoriIdentity.hash("email", "A@B.com"),
            SentoriIdentity.userKey(null, "A@B.com"),
        )
        // A blank id must fall through rather than win and yield null:
        // `user(id = "")` is a wiring mistake, not a decision to become
        // unaddressable.
        assertEquals(
            SentoriIdentity.hash("email", "a@b.com"),
            SentoriIdentity.userKey("  ", "a@b.com"),
        )
        assertNull(SentoriIdentity.userKey(null, null))
    }

    @Test
    fun oauthSubjectsAreLeftExactlyAsGiven() {
        assertEquals(" Ab ", SentoriIdentity.normalise("googleSub", " Ab "))
        assertEquals("X.Y", SentoriIdentity.normalise("appleSub", "X.Y"))
    }
}
