-- A device address that survives the vendor rotating its token.
--
-- `device_tokens` was unique on (project_id, provider, native_token),
-- so when APNs or FCM issued a new token for the same installation —
-- a reinstall, a restore from backup, a cleared data directory — the
-- next registration wrote a *new row* with a *new id*. Anything
-- holding the old id was pointing at nothing, and nothing told it.
--
-- That id is what a caller sends to. Handing out an address that
-- expires without notice, to a backend that has no way to learn it
-- expired, is the same failure this subsystem keeps producing: a
-- thing that stops working while looking like it works.
--
-- `install_id` is generated by the SDK on first run and persisted on
-- the device. It identifies the installation rather than the current
-- token, so a rotation becomes an UPDATE of `native_token` on the
-- row that already exists, and the address stays put.
--
-- The old uniqueness stays. Devices registered before this migration
-- have no install_id and must keep upserting the way they always
-- did; they pick one up the next time they register from an SDK that
-- sends one. Nothing is backfilled, because there is nothing to
-- backfill from — the value only exists on the device.

ALTER TABLE device_tokens ADD COLUMN install_id text;

CREATE UNIQUE INDEX idx_device_tokens_install
  ON device_tokens (project_id, install_id)
  WHERE install_id IS NOT NULL;

COMMENT ON COLUMN device_tokens.install_id IS
  'SDK-generated, device-persisted id for one app installation. The '
  'upsert key when present, so a rotated native_token updates this row '
  'rather than creating another. Never returned by any API: the public '
  'address is device_tokens.id (spToken), and an identifier that can '
  'claim a row must not be one that travels.';
