//! POST `/v1/push/tokens` — register device for push.
//!
//! UPSERT into `push_tokens` via push-provider's
//! `DeviceTokenStore::upsert`. Idempotent on (project_id, kind,
//! native_token).

use std::sync::Arc;

use axum::{Extension, Json, extract::State, http::StatusCode};
use sentori_ingest_token::IngestContext;
use sentori_push_provider::ProviderKind;
use serde::Deserialize;
use serde_json::{Value, json};
use tracing::{info, warn};

use crate::state::AppState;

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RegisterBody {
    /// Provider: `apns` / `fcm` / `webpush` / `hcm` / `mipush`.
    pub kind: String,
    /// Provider-native token (APNs hex, FCM reg id, web sub JSON).
    pub native_token: String,
    /// Optional environment hint (`production` / `sandbox` for APNs).
    #[serde(default)]
    pub env: Option<String>,
    /// The device's user, as the salted hash every event already
    /// carries (`events.user_key`). One identity, so "notify the
    /// people who hit this issue" is a join rather than a guess.
    /// Absent when the app registers before calling
    /// `sentori.user()` — such a device still receives broadcasts,
    /// it just is not addressable by issue.
    #[serde(default)]
    pub user_key: Option<String>,
    /// Host-supplied facts about the device — app version, locale,
    /// build channel. Shown on the device row in Settings ▸ Push so
    /// an integrator can confirm what they sent without asking us.
    ///
    /// `device_tokens.metadata` has existed since the table was
    /// created and nothing ever wrote to it: the SDK advertised the
    /// option, never sent it, and this struct had no field to receive
    /// it. Every row read `'{}'`.
    #[serde(default)]
    pub metadata: Option<Value>,
    /// What the host said about the *person*, from `sentori.user()`.
    ///
    /// Kept apart from `metadata`, which is about the device: the two
    /// have different writers and different lifetimes, and a send
    /// aimed at `plan = pro` should not match a device whose build
    /// channel happens to be called `pro`.
    ///
    /// Stored raw, unlike `user_key`. That pairing is deliberate — the
    /// identity stays unreadable and the attributes a campaign selects
    /// on stay readable.
    #[serde(default)]
    pub traits: Option<Value>,
    /// Which installation this is — generated by the SDK on first
    /// run and persisted on the device.
    ///
    /// The upsert key when present. Without it the row is keyed on
    /// the vendor's token, so a rotation (a reinstall, a restore,
    /// cleared app data) wrote a *new* row with a *new* id, and
    /// every backend holding the old one was addressing nothing.
    ///
    /// Never echoed back. The address a caller sends to is the row
    /// id; an identifier that can claim a row must not be one that
    /// travels through logs and other people's databases.
    #[serde(default)]
    pub install_id: Option<String>,
}

pub async fn handle(
    Extension(ctx): Extension<IngestContext>,
    State(state): State<Arc<AppState>>,
    Json(body): Json<RegisterBody>,
) -> (StatusCode, Json<Value>) {
    let Some(kind) = parse_kind(&body.kind) else {
        return (
            StatusCode::BAD_REQUEST,
            Json(json!({ "error": "invalid_kind", "got": body.kind })),
        );
    };

    // v0.2 canonical store is `device_tokens` (push.send /
    // subscribe_topic / preferences all query it). UPSERT here +
    // RETURNING id so client gets the actual device_tokens.id back.
    let new_id = uuid::Uuid::now_v7();

    // Two statements, because there are two unique keys and one
    // statement can only name one conflict target.
    //
    // The case worth spelling out is a device that has registered
    // before under a token that has since rotated. Its row exists,
    // keyed on the old token. An insert keyed on `install_id` would
    // not match it — it would collide with the *other* unique index
    // and fail outright. So the installation is looked up first, and
    // the token-keyed upsert is the fallback, which also adopts a row
    // that predates install ids and stamps one onto it.
    let mut hit: Option<(uuid::Uuid, bool)> = None;

    if let Some(install) = body.install_id.as_deref() {
        hit = update_by_installation(&state, &ctx, &body, install)
            .await
            .map(|id| (id, false));
    }

    let row = if let Some(found) = hit {
        Ok(found)
    } else {
        sqlx::query(
            // Five columns, five placeholders. It said `$6` for a year:
            // Postgres refuses the statement outright, so every device
            // registration this SDK has ever attempted came back 500 and
            // the product had zero push tokens for a reason that was
            // never "nobody turned it on".
            //
            // `revoked_at = NULL` is deliberate, and insight asked
            // whether it is: a device that registers again is a device
            // saying it is here, with a token the provider just issued
            // it. Both things that revoke a row — a provider reporting
            // the token dead, and the device revoking itself — are
            // answered by that. There is no third writer; nothing an
            // operator did is being undone.
            //
            // What was wrong was the trail it left. `quarantine_reason`
            // stayed in the metadata after the row came back, so the
            // device list showed a live device carrying "HTTP 404
            // UNREGISTERED" — a sentence about a token that has since
            // been replaced. It is dropped on the way back, and the
            // revival is stamped instead, because "this row was dead and
            // is not any more" is worth keeping.
            "INSERT INTO device_tokens \
             (id, project_id, provider, env, native_token, user_key, metadata, \
              install_id, traits) \
             VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7, '{}'::jsonb), $8, \
                     COALESCE($9, '{}'::jsonb)) \
             ON CONFLICT (project_id, provider, native_token) DO UPDATE SET \
            env = COALESCE(EXCLUDED.env, device_tokens.env), \
            user_key = COALESCE(EXCLUDED.user_key, device_tokens.user_key), \
            metadata = (CASE WHEN EXCLUDED.metadata = '{}'::jsonb \
                             THEN device_tokens.metadata ELSE EXCLUDED.metadata END \
                        - 'quarantine_reason') \
                       || CASE WHEN device_tokens.revoked_at IS NULL THEN '{}'::jsonb \
                               ELSE jsonb_build_object('revived_at', now()) END, \
            revoked_at = NULL, \
            install_id = COALESCE(EXCLUDED.install_id, device_tokens.install_id), \
            traits = COALESCE($9, device_tokens.traits), \
            last_seen_at = now(), \
            updated_at = now() \
             RETURNING id, (xmax = 0) AS is_new",
        )
        .bind(new_id)
        .bind(ctx.project_id)
        .bind(&body.kind)
        .bind(body.env.as_deref())
        .bind(&body.native_token)
        .bind(body.user_key.as_deref())
        // A re-register that omits metadata keeps what is already there
        // rather than blanking it — the same shape as `env` and
        // `user_key` above, so calling `register()` on every launch never
        // loses what an earlier launch reported.
        .bind(body.metadata.as_ref())
        .bind(body.install_id.as_deref())
        // Traits follow a different rule from metadata on purpose.
        // Absent keeps what is there; present replaces it, `{}`
        // included — because signing out has to be able to clear them,
        // and metadata has no equivalent (a device always has a
        // version and a locale).
        .bind(body.traits.as_ref())
        .fetch_one(&state.pool)
        .await
        .map(|r| {
            use sqlx::Row;
            (r.get("id"), r.try_get("is_new").unwrap_or(true))
        })
    };

    // Also UPSERT into the push-provider crate's push_tokens for
    // the legacy dispatcher path. Not load-bearing for v0.2; ignore.
    let _ = state
        .push_tokens
        .upsert(
            ctx.project_id,
            kind,
            &body.native_token,
            body.env.as_deref(),
            // The legacy store's `app_user_id` gets the same value:
            // two tables, one identity, rather than a second concept
            // to keep in sync.
            body.user_key.as_deref(),
        )
        .await;

    match row {
        Ok((device_id, is_new)) => {
            info!(
                project_id = %ctx.project_id,
                token_id = %device_id,
                is_new,
                "push.register_token upserted",
            );
            (
                StatusCode::ACCEPTED,
                // One name for the address. It shipped as `token_id`
                // and gained `spToken` beside it; carrying both was a
                // kindness to integrations that did not exist yet.
                Json(json!({
                    "spToken": device_id.to_string(),
                    "isNew": is_new,
                })),
            )
        }
        Err(e) => {
            warn!(error = %e, "push.register_token db_error");
            (
                StatusCode::INTERNAL_SERVER_ERROR,
                Json(json!({ "error": "internal" })),
            )
        }
    }
}

fn parse_kind(s: &str) -> Option<ProviderKind> {
    match s {
        "apns" => Some(ProviderKind::Apns),
        "fcm" => Some(ProviderKind::Fcm),
        "webpush" => Some(ProviderKind::WebPush),
        "hcm" => Some(ProviderKind::Hcm),
        "mipush" => Some(ProviderKind::MiPush),
        _ => None,
    }
}

/// The row for this installation, updated to whatever token the
/// vendor has issued it now.
///
/// A rotation is this UPDATE and nothing else: same row, same id, new
/// token. Returns `None` when this installation has never registered,
/// which is the caller's cue to fall through to the token-keyed
/// upsert — that path also adopts a row predating install ids and
/// stamps one onto it.
async fn update_by_installation(
    state: &Arc<AppState>,
    ctx: &IngestContext,
    body: &RegisterBody,
    install: &str,
) -> Option<uuid::Uuid> {
    use sqlx::Row;
    sqlx::query(
        "UPDATE device_tokens SET \
            native_token = $3, \
            provider = $4, \
            env = COALESCE($5, env), \
            user_key = COALESCE($6, user_key), \
            metadata = (CASE WHEN COALESCE($7, '{}'::jsonb) = '{}'::jsonb \
                             THEN metadata ELSE $7 END - 'quarantine_reason') \
                       || CASE WHEN revoked_at IS NULL THEN '{}'::jsonb \
                               ELSE jsonb_build_object('revived_at', now()) END, \
            traits = COALESCE($8, traits), \
            revoked_at = NULL, \
            last_seen_at = now(), \
            updated_at = now() \
         WHERE project_id = $1 AND install_id = $2 \
         RETURNING id",
    )
    .bind(ctx.project_id)
    .bind(install)
    .bind(&body.native_token)
    .bind(&body.kind)
    .bind(body.env.as_deref())
    .bind(body.user_key.as_deref())
    .bind(body.metadata.as_ref())
    .bind(body.traits.as_ref())
    .fetch_optional(&state.pool)
    .await
    .ok()
    .flatten()
    .map(|r| r.get("id"))
}
