// GENERATED MIRROR — do not edit.
// Source of truth: sdk/native/android/src/test/java/com/sentori/SentoriReplayRingTest.kt
// Run `node scripts/sync-native-core.mjs` after editing it.
package com.sentori

import java.io.File
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

/**
 * The ring against the TypeScript one, frame for frame.
 *
 * The vectors are generated by `scripts/gen-replay-vectors.mjs` from
 * `sdk/core/src/replay-ring.ts`, which is the source of truth for what
 * a replay is. Three implementations that disagree produce a replay of
 * a screen the user never saw, and the player renders a wrong frame
 * without complaint — so nothing but this says they agree.
 *
 * Robolectric for a real `org.json`: the stub `android.jar` answers
 * null from every method, and a comparison against that would pass on
 * anything.
 */
@RunWith(RobolectricTestRunner::class)
class SentoriReplayRingTest {

    private fun vectors(): JSONArray {
        // Walk up out of the module to the fixtures shared with iOS.
        var dir = File(System.getProperty("user.dir") ?: ".").absoluteFile
        var fixture: File? = null
        repeat(8) {
            val candidate = File(dir, "sdk/native/fixtures/replay-vectors.json")
            if (candidate.exists()) {
                fixture = candidate
                return@repeat
            }
            dir = dir.parentFile ?: dir
        }
        // Not a skip. A missing fixture means the cross-language gate
        // is not running, and a gate that quietly stops running is the
        // failure it exists to prevent.
        val f = requireNotNull(fixture) {
            "replay-vectors.json not found above ${System.getProperty("user.dir")}"
        }
        return JSONArray(f.readText())
    }

    private fun node(raw: JSONObject) = SentoriReplay.Node(
        x = raw.optDouble("x", 0.0),
        y = raw.optDouble("y", 0.0),
        w = raw.optDouble("w", 0.0),
        h = raw.optDouble("h", 0.0),
        kind = if (raw.has("kind")) raw.getString("kind") else null,
        text = if (raw.has("text")) raw.getString("text") else null,
        color = if (raw.has("color")) raw.getString("color") else null,
    )

    @Test
    fun `matches the TypeScript ring`() {
        val vectors = vectors()
        assert(vectors.length() >= 13) {
            "the fixture looks truncated — a file that reads as empty passes everything"
        }

        for (v in 0 until vectors.length()) {
            val vector = vectors.getJSONObject(v)
            val name = vector.optString("name")
            val options = vector.optJSONObject("options") ?: JSONObject()
            val ring = SentoriReplay.Ring(
                keyframeMs = options.optDouble("keyframeMs", 4000.0),
                windowMs = options.optDouble("windowMs", 60000.0),
                maxItems = options.optInt("maxItems", 1000),
            )

            val frames = vector.getJSONArray("frames")
            val emitted = vector.getJSONArray("emitted")
            assertEquals("$name: fixture is malformed", frames.length(), emitted.length())

            for (i in 0 until frames.length()) {
                val raw = frames.getJSONObject(i)
                val nodes = raw.getJSONArray("nodes")
                val frame = SentoriReplay.Frame(
                    ts = raw.optDouble("ts", 0.0),
                    width = raw.optDouble("width", 0.0),
                    height = raw.optDouble("height", 0.0),
                    nodes = (0 until nodes.length()).map { node(nodes.getJSONObject(it)) },
                )
                val got = ring.push(frame)
                if (emitted.isNull(i)) {
                    assertNull("$name: frame $i should have emitted nothing", got)
                } else {
                    assertNotNull("$name: frame $i emitted nothing, expected an entry", got)
                    same(got!!, emitted.getJSONObject(i), "$name frame $i")
                }
            }

            val wantRing = vector.getJSONArray("ring")
            val gotRing = ring.snapshot()
            assertEquals("$name: ring size", wantRing.length(), gotRing.size)
            for (i in 0 until wantRing.length()) {
                same(gotRing[i], wantRing.getJSONObject(i), "$name ring[$i]")
            }
        }
    }

    /**
     * Structural, not textual. Key order differs between a JS object
     * literal and a JSONObject, and the player parses — pinning byte
     * equality would pin something that does not matter and cannot be
     * held.
     */
    private fun same(got: Any?, want: Any?, path: String) {
        when {
            want is JSONObject -> {
                val g = got as? JSONObject ?: error("$path: expected an object, got $got")
                assertEquals(
                    "$path: keys differ",
                    want.keys().asSequence().toSortedSet(),
                    g.keys().asSequence().toSortedSet(),
                )
                for (key in want.keys()) same(g.get(key), want.get(key), "$path.$key")
            }
            want is JSONArray -> {
                val g = got as? JSONArray ?: error("$path: expected an array, got $got")
                assertEquals("$path: length", want.length(), g.length())
                for (i in 0 until want.length()) same(g.get(i), want.get(i), "$path[$i]")
            }
            want is Number -> assertEquals("$path", want.toDouble(), (got as Number).toDouble(), 0.0)
            else -> assertEquals("$path", want, got)
        }
    }

    @Test
    fun `two layers with the same geometry stay two nodes`() {
        // A page root and the fullscreen overlay covering it share
        // x/y/w/h. Keying on geometry alone collapsed them, and the
        // replay drew the page through the overlay.
        val nodes = listOf(
            SentoriReplay.Node(0.0, 0.0, 320.0, 640.0, kind = "view"),
            SentoriReplay.Node(0.0, 0.0, 320.0, 640.0, kind = "overlay"),
        )
        assertEquals(
            listOf("0,0,320,640#0", "0,0,320,640#1"),
            SentoriReplay.index(nodes).map { it.first },
        )
    }

    @Test
    fun `sub-pixel jitter is not a change`() {
        val a = SentoriReplay.Node(0.2, 0.4, 10.6, 10.9, kind = "a")
        val b = SentoriReplay.Node(0.7, 0.1, 10.2, 10.4, kind = "a")
        assertEquals(SentoriReplay.nodeKey(a, 0), SentoriReplay.nodeKey(b, 0))
    }
}
