// GENERATED MIRROR — do not edit.
// Source of truth: sdk/native/android/src/main/java/com/sentori/SentoriIdentity.kt
// Run `node scripts/sync-native-core.mjs` after editing it.
package com.sentori

import java.security.MessageDigest

/**
 * Turns a raw identity into the key that travels on the wire.
 *
 * Every event carries `userKey`, and a registered device carries the
 * same one — that join is what lets an issue reach the people it
 * happened to. The raw value never leaves the device; only this hash
 * does.
 *
 * Three implementations now compute it: TypeScript in
 * `sdk/core/src/identity.ts`, Swift, and this. They must agree byte
 * for byte. If they drift, a device stops matching the events from
 * the same person: the push reaches nobody and nothing reports it,
 * which is precisely why a second implementation is a bad idea unless
 * something is holding the three together.
 *
 * That something is `sdk/native/fixtures/identity-vectors.json`,
 * generated by the TypeScript module and asserted by both native
 * suites.
 *
 * The client hash is unsalted. The server layers its own per-scope
 * salt before storing a fingerprint; several comments in this
 * codebase call the client value "salted", and they are wrong.
 */
object SentoriIdentity {

    /**
     * SHA-256 of the normalised value, lowercase hex. `null` for an
     * empty or whitespace-only input — no key beats a meaningless
     * one, and the caller treats absent as "broadcast only".
     */
    @JvmStatic
    fun hash(keyType: String, value: String?): String? {
        if (value == null) return null
        val normalised = normalise(keyType, value)
        if (normalised.isEmpty()) return null
        val digest = MessageDigest.getInstance("SHA-256")
            .digest(normalised.toByteArray(Charsets.UTF_8))
        val out = StringBuilder(64)
        for (b in digest) {
            val v = b.toInt() and 0xff
            out.append(HEX[v ushr 4]).append(HEX[v and 0x0f])
        }
        return out.toString()
    }

    /**
     * The key for a user, matching `scope.ts`: the id if there is one,
     * otherwise the email. Not both — one device, one key.
     */
    @JvmStatic
    fun userKey(id: String?, email: String?): String? =
        hash("id", id) ?: hash("email", email)

    /**
     * Well-known normalisations, mirroring `normalise` in
     * `identity.ts`. A type this does not know about gets a plain
     * trim, which is that function's `default` branch.
     */
    /**
     * What the other two implementations strip.
     *
     * Kotlin's `trim()` uses `Character.isWhitespace`, which counts
     * neither U+00A0 (no-break space) nor U+FEFF (byte-order mark).
     * ECMAScript's `WhiteSpace` production counts both, so JavaScript
     * strips them. Swift's `.whitespacesAndNewlines` counts the first
     * and not the second, so it needed a fix of its own.
     *
     * Three languages, three definitions of blank. A value pasted from
     * a web page routinely carries these, and any of the defaults
     * would have made one device hash differently from its own events
     * — for one user, silently, on the path nobody watches.
     *
     * Caught by the shared vectors before it shipped, which is what
     * they are for.
     */
    private fun String.trimLikeTheOthers(): String =
        trim { it.isWhitespace() || it == '\u00a0' || it == '\ufeff' }

    @JvmStatic
    internal fun normalise(keyType: String, raw: String): String = when (keyType) {
        "email", "username" -> raw.trimLikeTheOthers().lowercase()
        // Everything that is not `+` or an ASCII digit goes, so
        // "+81 (90) 1234-5678" and "+819012345678" agree. Deliberately
        // not E.164 validation — that is the host's business; this
        // only removes formatting noise.
        "phone" -> raw.filter { it == '+' || it in '0'..'9' }
        // OAuth subject claims are opaque. Touching them would change
        // an identifier the provider defined.
        "googleSub", "appleSub", "metaSub" -> raw
        else -> raw.trimLikeTheOthers()
    }

    private val HEX = "0123456789abcdef".toCharArray()
}
