// GENERATED MIRROR — do not edit.
// Source of truth: sdk/native/android/src/main/java/com/sentori/SentoriReplayRing.kt
// Run `node scripts/sync-native-core.mjs` after editing it.
package com.sentori

import org.json.JSONArray
import org.json.JSONObject

/**
 * The last sixty seconds of what the screen looked like.
 *
 * The wireframe capture has been on both native platforms for a
 * while; the ring that decides what to keep of it lived only in the
 * React Native package, so a native-only app captured nothing. This
 * is the port, and it is checked frame for frame against vectors
 * generated by `sdk/core/src/replay-ring.ts` — three implementations
 * of a diff that disagree produce a replay of a screen the user never
 * saw, and the player renders a wrong frame without complaint.
 *
 * The caller owns the timer, and it must not be the main thread: the
 * wireframe capture posts to main internally, so a timer on main
 * waits on its own capture.
 */
object SentoriReplay {

    data class Node(
        val x: Double,
        val y: Double,
        val w: Double,
        val h: Double,
        val kind: String? = null,
        val text: String? = null,
        val color: String? = null,
    )

    data class Frame(
        val ts: Double,
        val width: Double,
        val height: Double,
        val nodes: List<Node>,
    )

    /**
     * Identity is geometry plus occurrence index in walk order.
     *
     * Geometry alone is not identity: a page root and the fullscreen
     * overlay covering it share x/y/w/h, and keying on that collapsed
     * them into one node — the overlay inherited the root's
     * z-position and the replay drew the page *through* it.
     *
     * Truncated to integers first, because sub-pixel jitter from a
     * layout pass that returns floats would make every node new on
     * every tick, turning a still screen into a stream of full
     * deltas.
     */
    fun nodeKey(node: Node, occurrence: Int): String =
        "${node.x.toInt()},${node.y.toInt()},${node.w.toInt()},${node.h.toInt()}#$occurrence"

    /** Ordered: a delta's arrays are compared against the TypeScript
     *  ring's, and a map would shuffle them. */
    fun index(nodes: List<Node>): List<Triple<String, Node, Int>> {
        val seen = mutableMapOf<String, Int>()
        return nodes.mapIndexed { at, node ->
            val base = nodeKey(node, 0).substringBefore('#')
            val occurrence = seen.getOrDefault(base, 0)
            seen[base] = occurrence + 1
            Triple("$base#$occurrence", node, at)
        }
    }

    class Delta {
        val added = mutableListOf<Triple<Node, Int, String>>()
        val changed = mutableListOf<Pair<Node, String>>()
        val removed = mutableListOf<Pair<Node, String>>()

        val count: Int
            get() = added.size + changed.size + removed.size
    }

    /**
     * Position is identity, so a node that moved is a removal and an
     * addition rather than a change. Only what a wireframe draws —
     * kind, colour, text — makes an existing node different.
     */
    fun delta(
        previous: List<Triple<String, Node, Int>>,
        current: List<Triple<String, Node, Int>>,
    ): Delta {
        val before = previous.associate { it.first to it.second }
        val now = current.map { it.first }.toSet()
        val out = Delta()
        for ((key, node, at) in current) {
            val was = before[key]
            if (was == null) {
                out.added.add(Triple(node, at, key))
                continue
            }
            if (was.kind.orEmpty() != node.kind.orEmpty() ||
                was.color.orEmpty() != node.color.orEmpty() ||
                was.text.orEmpty() != node.text.orEmpty()
            ) {
                out.changed.add(node to key)
            }
        }
        for ((key, node, _) in previous) {
            if (key !in now) out.removed.add(node to key)
        }
        return out
    }

    /** Past this share of the screen changing, a delta is a
     *  near-rewrite and a keyframe reconstructs more cheaply. */
    const val DELTA_TO_KEYFRAME_RATIO = 0.4

    /** Below this many nodes the ratio is noise — two rectangles
     *  moving on a three-node screen is not a screen transition. */
    const val KEYFRAME_RATIO_MIN_NODES = 10

    class Ring(
        private val keyframeMs: Double = 4000.0,
        private val windowMs: Double = 60000.0,
        private val maxItems: Int = 1000,
    ) {
        private val entries = ArrayDeque<JSONObject>()
        private var lastState: List<Triple<String, Node, Int>>? = null
        private var lastKeyframeTs = 0.0
        private val lock = Any()

        /**
         * Take a frame. Returns what was appended, or null when the
         * frame was identical to the last — a heartbeat with nothing
         * in it is dropped, because a minute of a still screen should
         * not cost 120 entries that reconstruct to the same picture.
         */
        fun push(frame: Frame): JSONObject? = synchronized(lock) {
            val state = index(frame.nodes)
            val cold = lastState == null
            val overdue = frame.ts - lastKeyframeTs >= keyframeMs

            val entry: JSONObject
            if (cold || overdue) {
                entry = keyframe(frame)
            } else {
                val diff = delta(lastState!!, state)
                if (diff.count == 0) return null
                if (state.size >= KEYFRAME_RATIO_MIN_NODES &&
                    diff.count >= state.size * DELTA_TO_KEYFRAME_RATIO
                ) {
                    entry = keyframe(frame)
                } else {
                    entry = JSONObject().apply {
                        put("ts", frame.ts)
                        put("kind", "delta")
                        put(
                            "added",
                            JSONArray(
                                diff.added.map { (node, at, id) ->
                                    encode(node).apply { put("at", at); put("id", id) }
                                }
                            )
                        )
                        put(
                            "changed",
                            JSONArray(diff.changed.map { (node, id) -> encode(node).put("id", id) })
                        )
                        put(
                            "removed",
                            JSONArray(
                                diff.removed.map { (node, id) ->
                                    JSONObject().apply {
                                        put("x", node.x); put("y", node.y)
                                        put("w", node.w); put("h", node.h)
                                        put("id", id)
                                    }
                                }
                            )
                        )
                    }
                }
            }

            entries.addLast(entry)
            evict(frame.ts)
            lastState = state
            return entry
        }

        fun snapshot(): List<JSONObject> = synchronized(lock) { entries.toList() }

        /**
         * Hand over the ring and start again cold, so the next frame
         * is a keyframe. Resuming with a delta would reconstruct
         * against a state the player no longer holds.
         */
        fun drain(): List<JSONObject> = synchronized(lock) {
            val out = entries.toList()
            entries.clear()
            lastState = null
            lastKeyframeTs = 0.0
            return out
        }

        private fun keyframe(frame: Frame): JSONObject {
            lastKeyframeTs = frame.ts
            return JSONObject().apply {
                put("ts", frame.ts)
                put("kind", "key")
                put("width", frame.width)
                put("height", frame.height)
                put("nodes", JSONArray(frame.nodes.map { encode(it) }))
            }
        }

        private fun evict(now: Double) {
            val cutoff = now - windowMs
            while (entries.isNotEmpty() && entries.first().optDouble("ts", 0.0) < cutoff) {
                entries.removeFirst()
            }
            while (entries.size > maxItems) entries.removeFirst()
        }
    }

    /**
     * Optional fields are left out rather than written as null, which
     * is what `JSON.stringify` does with an absent key — the player
     * reads "absent" and "null" the same way only by accident.
     */
    fun encode(node: Node): JSONObject = JSONObject().apply {
        put("x", node.x)
        put("y", node.y)
        put("w", node.w)
        put("h", node.h)
        node.kind?.let { put("kind", it) }
        node.text?.let { put("text", it) }
        node.color?.let { put("color", it) }
    }
}
